const mongoose = require("mongoose");

const Students = new mongoose.Schema(
  {
    studentName: String,
    admissionNo: String,
    rollNo: String,
    admissionDate: String,
    mobileNo: String,
    email: String,
    state: String,
    city: String,
    pincode: String,
    religion: String,
    cast: String,
    dob: String,
    gender: String,
    address: String,
    currentAddress: String,
    permanentAddress: String,
    categoryid: String,
    routid: String,
    schoolHouseId: String,
    bloodGroup: String,
    hostelRoomId: String,
    aadharNo: String,
    bankName: String,
    bankAccountNo: String,
    ifscCode: String,
    fatherName: String,
    fatherName: String,
    fatherOccuption: String,
    motherName: String,
    motherOccuption: String,
    guardianName: String,
    guardianOccuption: String,
    guardianAddress: String,
    guardianEmail: String,
    isActive: String,
    previousSchool: String,
    height: String,
    weight: String,
    measuremntDate: String,
    disReason: String,
    note: String,
  },
  {
    timestamps: { createdAt: true, updatedAt: true },
  }
);

module.exports = mongoose.model("Students", Students);
